<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
?>
<div class="text-gray-700 body-font bg-container-darker border-t border-container-darker shadow pb-4">
    <div class="container py-8 mx-auto">
        <div class="flex flex-wrap order-first gap-y-16">
            <?php foreach ($block->getChildNames() as $childName): ?>
                <?= $childName !== 'footer-copyright' ? $block->getBlockHtml($childName) : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="bg-container border-t border-b border-container">
        <div class="container py-6 mx-auto flex items-center justify-center sm:flex-row flex-col">
            <p class="mb-0">
                <?= $block->getChildHtml('copyright') ?>
            </p>
        </div>
    </div>
</div>

